### ISSUE TITLE
General `database_user` resource not working with postgresql, only `postgresql_database_user`

### ISSUE THREAD

**Issue by patcon** [chef-cookbooks/database#140]
Using `database` cookbook v4.0.3

```
database_user node['textsecure']['dbuser'] do
  provider Chef::Provider::Database::PostgresqlUser
  connection db_info
  password node['textsecure']['dbpass']
  action :create
end
```

The above throws the following error:

```
==> default: ================================================================================
==> default: Error executing action `create` on resource 'database_user[textsecure]'
==> default: ================================================================================
==> default: 
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `createdb' for Chef::Resource::DatabaseUser
```

The explicit `postgresql_database_user` resource works fine.

Might work at it later, but for now I've got an easy workaround :)

**Comment by PierreRambaud** [comment]
:+1:  Same problem here :)

**Comment by germs12** [comment]
:dancers: this works!  Thanks for the heads up.  Not a show stopper for me, but odd that using the generic `database_user` doesn't work.

**Comment by roblperry** [comment]
I made my stab at fixing this in https://github.com/chef-cookbooks/database/pull/186. I needed it fixed because https://github.com/openstack/cookbook-openstack-common/blob/82b4e9b3183f8171ae3b30b981735b71eba07e61/providers/database.rb uses database_user in this way.

I went through the extra step of correcting a couple of issues on the mysql side that have been preventing the CI from passing for some time now, so I'm hopeful that this gets merged in.

**Comment by patcon** [comment]
haha did my name get a cameo in the unit tests? i'm not actually a maintainer of this repo, so flattery ain't getting you anywhere, unfortunately :)

**Comment by roblperry** [comment]
lol....no, I had not even noticed.  I went with Krusty and Patrick from Sponge Bob to be easy for me to keep separate from Animal and Gonzo from the Muppets. 

....but thanks for reviewing!!!

**Comment by chewi** [comment]
I already did this in #177 but I guess yours is more thorough. I didn't add any new tests.

**Comment by roblperry** [comment]
Yours is much less verbose.  (less_code + same_functionality == better) But, I has already done the work before I thought to look for other having the issue, thus I had not spotted your solution until I was looking for something to support the need for any such change. 

That said, the one thing I didn't like about yours was that new resource you create doesn't capture anything of the original resource other than the resource name.  This not an issue ATM, but it did get me thinking about what might be a good generic solution to this issue. 

I favor the idea of making the specific resource (e.g. PostgresqlDatabaseUser) able to configure itself based on the less specific resource (e.g.  DatabaseUser).  But where to make the switch?  I don't know if load_current_resource might work, but it just seems semantically wrong.  I think the spot I currently favor is in the setter for new_resource.  

It does not lose all of the verbosity of my existing solution, but I think it is arguably more complete.

Thoughts?

**Comment by chewi** [comment]
I was just looking through the Resource class to see if there was anything there that we could use as this seems like a problem that would crop up a lot. How about the [load_from](https://github.com/chef/chef/blob/12.6.0/lib/chef/resource.rb#L548) method?

**Comment by roblperry** [comment]
Perfect!!!

So, now I'm thinking:
* Move setting of defaults to a method that is separate from initialize
* Override load_from to use the same method for setting defaults as initialize before calling super
* Override setting of the provider so that when the resource is set, it creates a new one and leverages load_from if the passed resource is not already of the desired class

Thoughts?

**Comment by chewi** [comment]
I was just thinking of adding this second line to my version but feel free to do something fancier. :grin: 

```ruby
pg_resource = Chef::Resource::PostgresqlDatabaseUser.new(@new_resource.name)
pg_resource.load_from(@new_resource)
```

**Comment by roblperry** [comment]
The direction I was jogging did not turn out well.  So, I'm leaving mine alone for the moment.

**Comment by tas50** [comment]
This should be fixed on master now

**Comment by chewi** [comment]
I feel we hadn't really finished discussing this but if @roblperry is happy then I'll leave it be.

**Comment by roblperry** [comment]
I'm happy enough to call the problem fixed, unless someone discovers for us that it is still broken.  We can always make it prettier later.

**Comment by patcon** [comment]
ditto on this merge seeming premature, but ok

**Comment by roblperry** [comment]
I wouldn't go as for as calling it "premature".  I **think** we all agree that the merged code is better than the prior code on master.  It not, then that is my error, not the mergers.  Meanwhile, I don't think we have closed any doors to making it better in the future.

e.g. Chewi could rewrite the latest action_create to be less verbose and still lean on the test code I wrote as well as my fix for the mysql issue that was causing CI to fail.  (which is probably the issue that stopped Chewi's pull request from being merged to begin with)

Considering the number of failed pull requests I see, I think I'm happy it was merged in ASAP.  Again, no doors were closed in the merging of this pull request. 

i.e. Thank you for merging tas50, but we might do a little follow up work still.

**Comment by jharveysmith** [comment]
Can we have a new release that includes this fix, please?

Thanks!

**Comment by iennae** [comment]
@jharveysmith there is a release that includes this fix.
@roblperry, @patcon, @chewi if you want to start a new issue thread to discuss improved functionality for database_user with postgresql if you are still interested in furthering this. I don't want to just merge #177 as is. Thank you for all your contributions, and nuanced discussions on this topic.
